# Generated by Django 5.2.3 on 2025-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
