# Generated by Django 5.2.3 on 2025-06-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_priorities', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('brand_affinities', models.JSONField(default=list)),
                ('price_sensitivity', models.JSONField(default=list)),
                ('shopping_frequency', models.CharField(default=3)),
                ('vibe', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
