# Generated by Django 5.2.3 on 2025-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twinprofile',
            options={'verbose_name': 'Twin Profile', 'verbose_name_plural': 'Twin Profiles'},
        ),
        migrations.RenameField(
            model_name='twinprofile',
            old_name='brand_affinities',
            new_name='shoppingTime',
        ),
        migrations.RemoveField(
            model_name='twinprofile',
            name='price_sensitivity',
        ),
        migrations.RemoveField(
            model_name='twinprofile',
            name='shopping_priorities',
        ),
        migrations.RemoveField(
            model_name='twinprofile',
            name='vibe',
        ),
        migrations.AddField(
            model_name='twinprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twinprofile',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twinprofile',
            name='favCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='twinprofile',
            name='reaction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='twinprofile',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twinprofile',
            name='shopping_frequency',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
